version: "3.9"

services:

  # DB TEST
  db-test:
    image: mysql:8.0.32
    env_file:
      - microservices/db/.env.db-test
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    container_name: db-test
    ports:
      - 33060:3306

  # DB 
  db:
    image: mysql:8.0.32
    env_file:
      - microservices/db/.env.db
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    container_name: db
    ports:
      - 33061:3306    

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
      - db-test
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: root    

    
# microservice passwordmanager
  passwordmanager:
    container_name: passwordmanager
    build:
      context: .
      dockerfile: microservices/passwordmanager/Dockerfile
    entrypoint: php -S 0.0.0.0:80 -t public
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - ./microservices/passwordmanager/project:/passwordmanager # cartella progetto
      - ./microservices/passwordmanager/xdebug/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # impostazioni per debug
      - ./microservices/passwordmanager/php/php.ini:/usr/local/etc/php/php.ini # impostazioni php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:80
        
# microservice prenotazione
  prenotazione:
    container_name: prenotazione
    build:
      context: .
      dockerfile: microservices/prenotazione/Dockerfile
    entrypoint: php -S 0.0.0.0:80 -t public
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - ./microservices/prenotazione/project:/prenotazione # cartella progetto
      - ./microservices/prenotazione/xdebug/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # impostazioni per debug
      - ./microservices/prenotazione/php/php.ini:/usr/local/etc/php/php.ini # impostazioni php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8001:80

