version: "3.9"

services:

  # DB TEST
  db-test:
    image: mysql:8.0.32
    env_file:
      - microservices/db/.env.db-test
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    container_name: db-test
    ports:
      - 33081:3306

  # DB 
  db:
    image: mysql:8.0.32
    env_file:
      - microservices/db/.env.db-hipalm
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    container_name: db
    ports:
      - 33082:3306

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
      - db-test
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

    
# microservice hipalm
  hipalm:
    container_name: hipalm
    build:
      context: .
      dockerfile: microservices/hipalm/Dockerfile
    entrypoint: php -S 0.0.0.0:80 -t public
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - ./microservices/hipalm/project:/hipalm # cartella progetto
      - ./microservices/hipalm/xdebug/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # impostazioni per debug
      - ./microservices/hipalm/php/php.ini:/usr/local/etc/php/php.ini # impostazioni php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:80
